### ISSUE TITLE
more examples?

### ISSUE THREAD

**Issue by garanews** [yukh1402/cti-stix-diamond-activity-attack-graph#16]
Hello,
do you know where I can try more examples to load and try?
I found these STIX 2.1 Threat Reports
https://oasis-open.github.io/cti-documentation/examples/example_json/apt1.json
https://oasis-open.github.io/cti-documentation/examples/example_json/poisonivy.json
but when try to load I am getting
Error: Minimum one Grouping SDO needs to be provided inside the Bundle.

**Comment by garanews** [comment]
I rephrase the question: do you have any other example different than the only one present under example folder?
I see schema in other stix available online missing what you use.
So I would ask if you have any other example to provide.

**Comment by yukh1402** [comment]
Unfortunately we only have the [Ryuk Ransomware](https://github.com/yukh1402/cti-stix-diamond-activity-attack-graph/blob/main/example/example-bundle.json) scenario at the moment. We are planning to provide additional attack scenarios until the end of this year.
