### ISSUE TITLE
Please allow '.json' file extension for STIX import Packages

### ISSUE THREAD

**Issue by packet-rat** [yukh1402/cti-stix-diamond-activity-attack-graph#20]
Many STIX 2.x files have '.json' extenstions. Please allow this file extension .

**Comment by yukh1402** [comment]
Hi, 
Thank you for bringing this to our attention. 

We can definitely implement this feature too. This will make the upload process easier.

**Comment by yukh1402** [comment]
Fixed in [T-15-Code-SCO](https://github.com/yukh1402/cti-stix-diamond-activity-attack-graph/pull/21)
